#!/usr/bin/env bash
#Install nginx on your web-01 server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
