#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname
HOSTNAME=$(hostname)

# Create a configuration file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        add_header X-Served-By $HOSTNAME;
        return 200 'Hello, World!';
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx