#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install haproxy
echo "frontend Youssef-frontend
        bind *:80
        mode http
        default_backend Youssef-backend
backend Youssef-backend
        balance roundrobin
        server web-01 54.152.60.211:80 check
        server web-02 34.229.71.198:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
