#!/usr/bin/env bash
#Bash script displaying numbers from 1 to 100.
for ((num = 1; num <= 100; num++))
do
    if [ $((num % 15)) == 0 ]; then
        echo "FizzBuzz"
    elif [ $((num % 3)) == 0 ]; then
        echo "Fizz"
    elif [ $((num % 5)) == 0 ]; then
        echo "Buzz"
    else
        echo "$num"
    fi
done