#!/usr/bin/env bash
#This script is displaying the content of the file /etc/passwd
while IFS=: read -r usrname passwd uid gid gecos homedir shell  ; do
    echo "The user $usrname is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $gecos"
done < /etc/passwd