#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes:
H=0
while [ $H -le 12 ]
do
    echo "Hour: $H"
    ((H++))
M=1
while [ $M -le 59 ]
do
    echo "$M"
    ((M++))
done
done
