#!/usr/bin/env bash
# This script is displaying The content of the current directory
# In a list format
for file in *
do
    if [ -f "$file" ] && [ "$file" != "${file#*-}" ]
    then
        echo "${file#*-}"
    fi
done
