#!/usr/bin/env bash
#change the home IP address
cp /etc/hosts ~/hosts.recent
sed -i 's/^127.0.0.1.*/127.0.0.2 localhost/g' ~/hosts.recent
echo "8.8.8.8 facebook.com" >> ~/hosts.recent
cp -f ~/hosts.recent /etc/hosts