#!/usr/bin/env bash
#Bash script fixing this container so that Nginx is running as the nginx user
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx restart
ps aux | grep nginx
nc -z 0 8080 && echo "Nginx is running on port 8080 as user nginx."
